apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nessie-data
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: projectnessie/nessie
        ports:
        - containerPort: 19120
        volumeMounts:
        - name: nessie-data
          mountPath: /var/lib/nessie
      volumes:
      - name: nessie-data
        persistentVolumeClaim:
          claimName: nessie-data