kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/data"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXNkYg==      # base64-encoded "postgresdb"
  POSTGRES_USER: YWRtaW4=         # base64-encoded "admin"
  POSTGRES_PASSWORD: YWRtaW4=     # base64-encoded "admin"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: init-postgres
          image: postgres:10.1
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /var/lib/postgresql/data
              chown 999:999 /var/lib/postgresql/data
              chmod 700 /var/lib/postgresql/data
              export PGDATA=/var/lib/postgresql/data
              export POSTGRES_DB=postgresdb
              export POSTGRES_USER=admin
              export POSTGRES_PASSWORD=admin
              /usr/local/bin/docker-entrypoint.sh postgres &
              sleep 10
              killall postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      containers:
        - name: postgres
          image: postgres:10.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          command:
            - "postgres"
            - "-c"
            - "wal_level=logical"
          securityContext:
            runAsUser: 999
            runAsGroup: 999
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres