apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc-data
  namespace: kafka
spec:
  resources:
    requests:
      storage: 4Gi 
  accessModes:
    - ReadWriteOnce
  # storageClassName: hdd-storageclass

---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nm-zookeeper-pvc-log
#   namespace: nm-kafka
# spec:
#   resources:
#     requests:
#       storage: 2Gi 
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: worker02-nfs-storageclass

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.4.0
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_DATA_DIR
          value: "/var/lib/zookeeper/data"
        # - name: ZOOKEEPER_LOG_DIR
        #   value: "/var/lib/zookeeper/log"
        volumeMounts:
        - mountPath: /var/lib/zookeeper/data
          name: zookeeper-data
        # - mountPath: /var/lib/zookeeper/log
        #   name: zookeeper-log
      volumes:
        - name: zookeeper-data
          persistentVolumeClaim:
            claimName: zookeeper-pvc-data
        # - name: zookeeper-log
        #   persistentVolumeClaim:
        #     claimName: nm-zookeeper-pvc-log

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
