apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
spec:
  selector:
    app: kafka-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort  # Hoặc NodePort nếu không dùng cloud

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "local-kafka"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS
              value: "thh-kafka-bootstrap.kafka.svc:9092"  # Địa chỉ Kafka Cluster
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: thh-zookeeper-client:2181
